### 1. LOGIN SUCCESS (Admin)
# Checks if the admin user can authenticate
POST http://localhost:7002/login
Content-Type: application/json

{
  "username": "admin_ebu",
  "password": "admin123"
}


### 2. LOGIN SUCCESS (HOD Romania)
POST http://localhost:7002/login
Content-Type: application/json

{
  "username": "hod_romania",
  "password": "hod123"
}


### 3. LOGIN FAIL (Wrong Password)
# Should return 401 Unauthorized or a null user object
POST http://localhost:7002/login
Content-Type: application/json

{
  "username": "admin_ebu",
  "password": "wrong_password"
}